spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/calendar_app
    username: postgres
    password: postgres
    name: calendar
    driver-class-name: org.postgresql.Driver
doma:
  dialect: postgres